#!/usr/bin/env node
// MemoryPets client bundle builder.
//
// Reads the source ESM module at packages/client/lib/client.mjs and emits a
// CommonJS-style factory bundle at packages/client/lib/client.bundle.js
// suitable for loading inside the dsh browser kernel via window.__ModuleLoader__.
//
// The transformation is deliberately simple (no AST, no Babel):
//   1. Strip `import * as React from 'react';` (React is provided by the kernel).
//   2. Rewrite `export const/function/let/var/class` into a plain declaration.
//   3. Rewrite `export default X` into `const __default = X`.
//   4. Hoist `export { a, b, c }` into per-name assignments inside the factory.
//   5. Wrap the resulting source in a factory function that exposes the
//      declared names via `exports.<name>`.
//
// Usage:
//   node scripts/build-client.mjs                 # write bundle to packages/client/lib/
//   node scripts/build-client.mjs --check         # verify and exit non-zero on drift

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..');
const SRC = join(REPO_ROOT, 'packages/client/lib/client.mjs');
const DST = join(REPO_ROOT, 'packages/client/lib/client.bundle.js');

const CHECK_ONLY = process.argv.includes('--check');

if (!existsSync(SRC)) {
  console.error(`[build-client] source not found: ${SRC}`);
  process.exit(1);
}

const srcRaw = readFileSync(SRC, 'utf8');

// Step 1: strip the React import. We only need this exact pattern; any other
// imports would be a build-time error since the kernel has no bundler.
const REACT_IMPORT = /^import\s+\*\s+as\s+React\s+from\s+['"]react['"];\s*\n/m;
if (!REACT_IMPORT.test(srcRaw)) {
  console.warn('[build-client] WARNING: source does not contain expected `import * as React from "react"` line.');
}
let src = srcRaw.replace(REACT_IMPORT, '');

// Step 2 + 3 + 4: rewrite exports. We do this with a small character-level
// scan so multi-line / braced declarations stay intact.
const exportedNames = new Set();
const REWRITE = /(^|[^.\w$])(export)\s+(default|const|let|var|function|class|async\s+function)\b/g;

function transform(srcText) {
  let out = '';
  let i = 0;
  let hasDefault = false;
  while (i < srcText.length) {
    // Try to match `export { a, b as c }` (a single line, possibly).
    const m = srcText.slice(i).match(/^export\s*\{([^}]+)\}\s*;?/);
    if (m) {
      const names = m[1]
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .map((s) => {
          // supports `a as b`
          const parts = s.split(/\s+as\s+/);
          return { local: parts[0].trim(), exported: (parts[1] || parts[0]).trim() };
        });
      for (const n of names) {
        exportedNames.add(n.exported);
        out += `const ${n.exported} = ${n.local};\n`;
      }
      i += m[0].length;
      continue;
    }
    // Try to match `export const/function/let/var/class/async function NAME`
    const decl = srcText
      .slice(i)
      .match(/^export\s+(async\s+function\s+|function\s+|class\s+|const\s+|let\s+|var\s+)([A-Za-z_$][\w$]*)/);
    if (decl) {
      const kw = decl[1].replace(/\s+$/, '');
      const name = decl[2];
      exportedNames.add(name);
      // Drop the `export ` prefix; emit the rest verbatim.
      out += kw + ' ' + name;
      i += ('export ' + decl[1] + decl[2]).length;
      continue;
    }
    // Try to match `export default <expr>` — capture until end of statement.
    const def = srcText.slice(i).match(/^export\s+default\s+/);
    if (def) {
      out += 'const __default = ';
      hasDefault = true;
      exportedNames.add('default');
      i += def[0].length;
      continue;
    }
    out += srcText[i];
    i++;
  }
  return { code: out, hasDefault };
}

// If the source already declares `const __default = ` (because it had
// `export default X`), don't emit a second one in the trailer.
const { code: transformed, hasDefault } = transform(src);
src = transformed;

// Step 5: compose the factory bundle.
const banner = `// ⚠️  AUTO-GENERATED by \`node scripts/build-client.mjs\`.
// Source: packages/client/lib/client.mjs
// Do not edit this file directly; modify the source and rerun.
//
// This file is served by dsh-client-modules at
//   /plugins/@memorypets/client/client.js?rev=...
// The browser kernel prepends window.__ModuleLoader__ before any client
// bundle, so this wrapper wires our plugin exports into the dsh client
// cordis fiber on the browser side.
//
// All "import" statements become synchronous \`require(...)\` calls against
// the shared Platform Module table (react / cordis / ui-slots etc.).
`;

const trailer = `
    ${hasDefault ? '' : 'const __default = { name, inject, apply };\n    '}${Array.from(exportedNames)
      .filter((n) => n !== 'default')
      .map((n) => `exports.${n} = ${n};`)
      .join('\n    ')}
    exports.default = __default;

    return module.exports;
  },
});
`;

const body = `window.__ModuleLoader__.load({
  id: '@memorypets/client',
  factory: (require) => {
    'use strict';
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });

    var React = require('react');

${src
  .split('\n')
  .map((l) => '    ' + l)
  .join('\n')}
${trailer}`;

const out = banner + body + '\n';

if (CHECK_ONLY) {
  const current = existsSync(DST) ? readFileSync(DST, 'utf8') : '';
  if (current === out) {
    console.log('[build-client] bundle is up to date.');
    process.exit(0);
  } else {
    console.error('[build-client] bundle is OUT OF DATE. Run `pnpm build:client` to refresh.');
    process.exit(2);
  }
}

writeFileSync(DST, out, 'utf8');
console.log(`[build-client] wrote ${DST} (${out.length} bytes, exports: ${Array.from(exportedNames).join(', ')})`);

// Syntax check.
const check = spawnSync('node', ['--check', DST], { encoding: 'utf8' });
if (check.status !== 0) {
  console.error('[build-client] node --check failed:\n' + check.stderr);
  process.exit(3);
}
console.log('[build-client] node --check passed.');